name: Run Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-ubuntu:
    name: Run tests on Ubuntu
    runs-on: ubuntu-latest
    
    steps:
    - name: get code
      uses: actions/checkout@v4
      
    - name: install py
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Run unit tests
      run: |
        python -m unittest test_geometric_lib.py

  test-windows:
    name: Run tests on Windows
    runs-on: windows-latest
    
    steps:
    - name: get code
      uses: actions/checkout@v4
      
    - name: install py
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Run unit tests
      run: |
        python -m unittest test_geometric_lib.py